
title: "Winston Yallow"
description: "Game Development Blog"
twitter_name: "WinstonYallow"

title_animation:
  width: 180px
  time: 400ms
logo_url: /media/logo.png

excerpt_separator: <!--more-->

repository: winston-yallow/winston-yallow.github.io

plugins:
  - "jekyll-github-metadata"
  - "jekyll-octicons"
  - "jekyll-feed"
