
title: "Game Development Blog"
description: "by Winston Yallow"
twitter_name: "WinstonYallow"

repository: winston-yallow/winston-yallow.github.io

plugins:
  - "jekyll-github-metadata"
  - "jekyll-octicons"
  - "jekyll-feed"
