
title: "Winston Yallow"
title_animation:
  width: 180px
  time: 400ms
description: "Game Development Blog"
twitter_name: "WinstonYallow"

repository: winston-yallow/winston-yallow.github.io

plugins:
  - "jekyll-github-metadata"
  - "jekyll-octicons"
  - "jekyll-feed"
